name: Autograding Tests
'on':
  - repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install dependencies
      run: pip install pandas==2.1.4 jupyter==1.0.0 networkx==3.2.1

    - name: Q0 Test
      uses: classroom-resources/autograding-io-grader@v1
      id: q0-test
      with:
        test-name: Getting Started
        command: python ok --score -q q0
        input: ''
        expected-output: 'Total: 1.0'
        comparison-method: contains
        timeout: 10
        max-score: 1
    - name: Q1 Test
      uses: classroom-resources/autograding-io-grader@v1
      id: q1-test
      with:
        test-name: Calculations
        command: python ok --score -q q1
        input: ''
        expected-output: 'Total: 1.0'
        comparison-method: contains
        timeout: 10
        max-score: 1
    - name: Q2 Test
      uses: classroom-resources/autograding-io-grader@v1
      id: q2-test
      with:
        test-name: Variables
        command: python ok --score -q q2
        input: ''
        expected-output: 'Total: 1.0'
        comparison-method: contains
        timeout: 10
        max-score: 1
    - name: Q3 Test
      uses: classroom-resources/autograding-io-grader@v1
      id: q3-test
      with:
        test-name: Strings
        command: python ok --score -q q3
        input: ''
        expected-output: 'Total: 1.0'
        comparison-method: contains
        timeout: 10
        max-score: 1
    - name: Q4 Test
      uses: classroom-resources/autograding-io-grader@v1
      id: q4-test
      with:
        test-name: Objects
        command: python ok --score -q q4
        input: ''
        expected-output: 'Total: 1.0'
        comparison-method: contains
        timeout: 10
        max-score: 1
    - name: Q5 Test
      uses: classroom-resources/autograding-io-grader@v1
      id: q5-test
      with:
        test-name: Comparisons
        command: python ok --score -q q5
        input: ''
        expected-output: 'Total: 1.0'
        comparison-method: contains
        timeout: 10
        max-score: 1
    - name: Q6 Test
      uses: classroom-resources/autograding-io-grader@v1
      id: q6-test
      with:
        test-name: Conditional Statements
        command: python ok --score -q q6
        input: ''
        expected-output: 'Total: 1.0'
        comparison-method: contains
        timeout: 10
        max-score: 1
    - name: Q7 Test
      uses: classroom-resources/autograding-io-grader@v1
      id: q7-test
      with:
        test-name: While loops
        command: python ok --score -q q7
        input: ''
        expected-output: 'Total: 1.0'
        comparison-method: contains
        timeout: 10
        max-score: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:        
          Q0-TEST_RESULTS: "${{steps.q0-test.outputs.result}}"
          Q1-TEST_RESULTS: "${{steps.q1-test.outputs.result}}"
          Q2-TEST_RESULTS: "${{steps.q2-test.outputs.result}}"
          Q3-TEST_RESULTS: "${{steps.q3-test.outputs.result}}"
          Q4-TEST_RESULTS: "${{steps.q4-test.outputs.result}}"
          Q5-TEST_RESULTS: "${{steps.q5-test.outputs.result}}"
          Q6-TEST_RESULTS: "${{steps.q6-test.outputs.result}}"
          Q7-TEST_RESULTS: "${{steps.q7-test.outputs.result}}"
      with:
          runners: q0-test,q1-test,q2-test,q3-test,q4-test,q5-test,q6-test,q7-test
