name: Autograding Tests
on:
  - push
  - workflow_dispatch
  - repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install dependencies
      run: pip install pandas==2.1.4 jupyter==1.0.0 networkx==3.2.1

    - name: Run q0
      uses: classroom-resources/autograding-io-grader@v1
      id: q0test
      with:
        test-name: Getting Started
        command: python ok --score -q q0
        input: ''
        expected-output: 'Total: 1.0'
        comparison-method: contains
        timeout: 10
        max-score: 1
    - name: Run q1
      uses: classroom-resources/autograding-io-grader@v1
      id: q1test
      with:
        test-name: Calculations
        command: python ok --score -q q1
        input: ''
        expected-output: 'Total: 1.0'
        comparison-method: contains
        timeout: 10
        max-score: 1
    - name: Run q2
      uses: classroom-resources/autograding-io-grader@v1
      id: q2test
      with:
        test-name: Variables
        command: python ok --score -q q2
        input: ''
        expected-output: 'Total: 1.0'
        comparison-method: contains
        timeout: 10
        max-score: 1
    - name: Run q3
      uses: classroom-resources/autograding-io-grader@v1
      id: q3test
      with:
        test-name: Strings
        command: python ok --score -q q3
        input: ''
        expected-output: 'Total: 1.0'
        comparison-method: contains
        timeout: 10
        max-score: 1
    - name: Run q4
      uses: classroom-resources/autograding-io-grader@v1
      id: q4test
      with:
        test-name: Objects
        command: python ok --score -q q4
        input: ''
        expected-output: 'Total: 1.0'
        comparison-method: contains
        timeout: 10
        max-score: 1
    - name: Run q5
      uses: classroom-resources/autograding-io-grader@v1
      id: q5test
      with:
        test-name: Getting Started
        command: python ok --score -q q5
        input: ''
        expected-output: 'Total: 1.0'
        comparison-method: contains
        timeout: 10
        max-score: 1
    - name: Run q6
      uses: classroom-resources/autograding-io-grader@v1
      id: q6test
      with:
        test-name: Getting Started
        command: python ok --score -q q6
        input: ''
        expected-output: 'Total: 1.0'
        comparison-method: contains
        timeout: 10
        max-score: 1
    - name: Run q7
      uses: classroom-resources/autograding-io-grader@v1
      id: q7test
      with:
        test-name: Getting Started
        command: python ok --score -q q7
        input: ''
        expected-output: 'Total: 1.0'
        comparison-method: contains
        timeout: 10
        max-score: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:        
          Q0_RESULTS: "${{steps.q0test.outputs.result}}"
          Q1_RESULTS: "${{steps.q1test.outputs.result}}"
          Q2_RESULTS: "${{steps.q2test.outputs.result}}"
          Q3_RESULTS: "${{steps.q3test.outputs.result}}"
          Q4_RESULTS: "${{steps.q4test.outputs.result}}"
          Q5_RESULTS: "${{steps.q5test.outputs.result}}"
          Q6_RESULTS: "${{steps.q6test.outputs.result}}"
          Q7_RESULTS: "${{steps.q7test.outputs.result}}"
      with:
          runners: q0test,q1test,q2test,q3test,q4test,q5test,q6test,q7test